/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_tetrisapp_free: (a: number, b: number) => void;
export const tetrisapp_get_level: (a: number) => number;
export const tetrisapp_get_lines: (a: number) => number;
export const tetrisapp_get_score: (a: number) => number;
export const tetrisapp_get_state: (a: number) => number;
export const tetrisapp_key_down: (a: number, b: number, c: number) => void;
export const tetrisapp_key_up: (a: number, b: number, c: number) => void;
export const tetrisapp_new: (a: any, b: any, c: any) => [number, number, number];
export const tetrisapp_on_blur: (a: number) => void;
export const tetrisapp_render_initial: (a: number) => void;
export const tetrisapp_set_on_score_update: (a: number, b: any) => void;
export const tetrisapp_set_on_state_change: (a: number, b: any) => void;
export const tetrisapp_start_game_loop: (a: number) => [number, number];
export const __wbg_tetris_free: (a: number, b: number) => void;
export const get_color: (a: number) => [number, number];
export const tetris_get_board_cells: (a: number) => [number, number];
export const tetris_get_ghost_cells: (a: number) => [number, number];
export const tetris_get_hold_cells: (a: number) => [number, number];
export const tetris_get_level: (a: number) => number;
export const tetris_get_lines: (a: number) => number;
export const tetris_get_next_cells: (a: number) => [number, number];
export const tetris_get_piece_cells: (a: number) => [number, number];
export const tetris_get_score: (a: number) => number;
export const tetris_get_state: (a: number) => number;
export const tetris_is_hold_available: (a: number) => number;
export const tetris_key_down: (a: number, b: number) => void;
export const tetris_key_up: (a: number, b: number) => void;
export const tetris_new: () => number;
export const tetris_on_blur: (a: number) => void;
export const tetris_update: (a: number, b: number) => number;
export const wasm_bindgen__convert__closures_____invoke__hc1ac6a06dab0941c: (a: number, b: number, c: number) => void;
export const wasm_bindgen__closure__destroy__h05f94b76025885e2: (a: number, b: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
